name: Call Me
on:
  workflow_dispatch:  
  workflow_call: 
jobs:
  launched:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello
        run: echo "Hello, World!"